version: '3.3'

services:
  consul_fid:
    ports:
      - '8080:8080'
    build:
      context: .
    volumes:
      - type: bind
        source: ./reports # Change this to your mount folder
        target: /fiddlemain/reports



